# Generated by Django 5.2.2 on 2025-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News_Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="TitleNews")),
                (
                    "short_info",
                    models.CharField(max_length=200, verbose_name="Short Description"),
                ),
                ("text", models.TextField(verbose_name="TextNews")),
                (
                    "publish_date",
                    models.DateTimeField(verbose_name="Date of publication"),
                ),
            ],
        ),
    ]
